spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-crud?createDatabaseIfNotExist=true&serverTimezone=UTC #jdbc:h2:mem:testdb
    username: root
    password: root
    #driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/testdata

#server:
#  error:
#    include-stacktrace: never
#    include-message: never